"""Initial Schema

Revision ID: 632ba131723a
Revises: 
Create Date: 2026-02-19 13:10:02.421713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '632ba131723a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_actor_id'), 'auditlog', ['actor_id'], unique=False)
    op.create_index(op.f('ix_auditlog_target_id'), 'auditlog', ['target_id'], unique=False)
    op.create_table('folder',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_name'), 'folder', ['name'], unique=False)
    op.create_index(op.f('ix_folder_parent_id'), 'folder', ['parent_id'], unique=False)
    op.create_table('standard',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_name'), 'standard', ['name'], unique=False)
    op.create_table('document',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('minio_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_filename'), 'document', ['filename'], unique=False)
    op.create_index(op.f('ix_document_folder_id'), 'document', ['folder_id'], unique=False)
    op.create_index(op.f('ix_document_hash'), 'document', ['hash'], unique=False)
    op.create_table('standardversion',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standardassignment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('FOLDER', 'DOCUMENT', name='targettype'), nullable=False),
    sa.Column('standard_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standardversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standardassignment_target_id'), 'standardassignment', ['target_id'], unique=False)
    op.create_index(op.f('ix_standardassignment_target_type'), 'standardassignment', ['target_type'], unique=False)
    op.create_table('validationresult',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'WARN', name='validationstatus'), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standardversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validationresult_status'), 'validationresult', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validationresult_status'), table_name='validationresult')
    op.drop_table('validationresult')
    op.drop_index(op.f('ix_standardassignment_target_type'), table_name='standardassignment')
    op.drop_index(op.f('ix_standardassignment_target_id'), table_name='standardassignment')
    op.drop_table('standardassignment')
    op.drop_table('standardversion')
    op.drop_index(op.f('ix_document_hash'), table_name='document')
    op.drop_index(op.f('ix_document_folder_id'), table_name='document')
    op.drop_index(op.f('ix_document_filename'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_standard_name'), table_name='standard')
    op.drop_table('standard')
    op.drop_index(op.f('ix_folder_parent_id'), table_name='folder')
    op.drop_index(op.f('ix_folder_name'), table_name='folder')
    op.drop_table('folder')
    op.drop_index(op.f('ix_auditlog_target_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_actor_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
