"""add_cascade_delete

Revision ID: c69156db3493
Revises: 632ba131723a
Create Date: 2026-02-23 17:30:32.647444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c69156db3493'
down_revision: Union[str, None] = '632ba131723a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('validationresult_document_id_fkey'), 'validationresult', type_='foreignkey')
    op.create_foreign_key(None, 'validationresult', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validationresult', type_='foreignkey')
    op.create_foreign_key(op.f('validationresult_document_id_fkey'), 'validationresult', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###
